### ISSUE TITLE
systemd service template compiles incorrectly

### ISSUE THREAD

**Issue by lchski** [debops/ansible-docker#13]
I’m running a default setup of this role on a Debian jessie machine. All tasks run successfully. However, the `docker` service never starts.

`systemctl status -l docker.service` yields the following:

```
root@hannibal:~# systemctl -l status docker.service
● docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled)
   Active: failed (Result: exit-code) since Fri 2016-07-15 22:47:09 EDT; 42min ago
  Process: 31330 ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver aufs --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=generic (code=exited, status=1/FAILURE)
 Main PID: 31330 (code=exited, status=1/FAILURE)

Jul 15 22:47:09 hannibal docker[31330]: docker: 'daemon' is not a docker command. See 'docker --help'.
Jul 15 22:47:09 hannibal systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jul 15 22:47:09 hannibal systemd[1]: Unit docker.service entered failed state.
```

Digging into the `/etc/systemd/system/docker.service` file, I see that the script calls `/usr/bin/docker daemon`. This doesn’t exist for the version of Docker installed to my machine—`1.6.2`—and should be `/usr/bin/docker -d`.

[Looking at the template which generates this service file](https://github.com/debops/ansible-docker/blob/master/templates/etc/systemd/system/docker.service.j2#L11-L15), I see that it decides whether to use `docker daemon` or `docker -d` depending on the version of Docker installed. This makes sense, but doesn’t appear to be working: the version installed on my machine is `1.6.2`, which is less than `1.8`, so it should be using `docker -d`, not `docker daemon`. Clearly `version_compare` is failing to parse the version value properly.

Looking then at [the place where the Docker version is registered for checking with `version_compare`](https://github.com/debops/ansible-docker/blob/master/tasks/main.yml#L45-L52), I see a command I can run to see what string is being passed to `version_compare`: `dpkg-query -W -f='${Version}\n' '{{ ("docker-engine" if docker_upstream|d() else "docker.io") }}' | cut -d- -f1`. Because I’m not using the upstream package, I sub in `docker.io` for the templated string, and get the following:

```
root@hannibal:~# dpkg-query -W -f='${Version}\n' 'docker.io' | cut -d- -f1
1.6.2~dfsg1
```

So it would appear that `version_compare` uses the string `1.6.2~dfsg1` to decide which script to call; though I haven’t dug any further than this, there might be something here which is causing this problem.

**Comment by drybjed** [comment]
Thank you for the bug report and the research, much appreciated!

I've noticed issues with `version_compare` using different version formats, especially `x.y` vs `x.y.z`, working on the new PHP role, perhaps it's the same thing. I wonder if it would work with `version_compare` using `1.8.0` for comparsion?

I'll try to find solution and fix the issue soon.

**Comment by tallandtree** [comment]
I have a fix for this almost ready.

**Comment by drybjed** [comment]
This issue seems to be fixed for some time, certainly with the latest version of the role. I'm closing it, let me know it's still present.
