### ISSUE TITLE
Support for iptables chain DOCKER-ISOLATION 

### ISSUE THREAD

**Issue by tallandtree** [debops/ansible-docker#18]
Docker 1.10 and above implemented a new iptables chain "DOCKER-ISOLATION". With debops.ferm implementation, I need to restart the docker daemon after a firewall change managed by debops to be able to use docker networks again.

Support for DOCKER-ISOLATION is highly desired.

**Comment by drybjed** [comment]
DebOps uses [ferment](https://github.com/diefans/ferment) to support Docker firewall rules with `ferm`. You should request that feature upstream. Or, I suppose that we could fork `ferment` to our own GitHub repo and implement it there. Upstream however would be better.

**Comment by drybjed** [comment]
Hmm, when `debops.docker` is enabled on a host, it should enable `ferment` support in the `ferm` configuration. Can you check if the script is installed and used by `ferm`?

**Comment by tallandtree** [comment]
I think so: there is a script:
`/usr/local/lib/docker-ferment-wrapper`
which refers to:
`/usr/local/bin/ferment` 
which uses python ferment.scripts to retrieve the docker firewall rules. But the ferment.scripts and template do not support DOCKER-ISOLATION. There is only a DOCKER chain. I've got the latest (and only version) ferment-0.0.1.
Maybe I should instead create a change request for the ferment.scripts template. 

Main issue is that the docker network layer does not seem very stable yet, which makes it difficult to automate. After each update (either ansible, python modules, or docker) you need to revise your scripts/playbooks.

**Comment by drybjed** [comment]
@tallandtree One idea you could explore is to disable `debops.ferm` role and the `ferm` firewall, see if that helps with Docker. Does Docker allow some kind of hooks for setting up the firewall so that it doesn't need to be restarted on each change? Or maybe can you run a command that coerces the Docker to do whatever it does to configure the `iptables` rules it needs?

**Comment by drybjed** [comment]
This issue should be solved in the latest version of the `debops.docker` role. When upstream Docker is disabled, `ferment` is not installed and instead a `ferm` post-hook script that restarts the Docker service is added by the role. This should help with management of the firewall, although it makes the containers restart on firewall changes... Not sure how to solve that for the moment. I'm closing this issue now.

**Comment by tallandtree** [comment]
Restart could be prevented by setting the docker daemon option live-restore to true. See: https://docs.docker.com/engine/admin/live-restore/.

**Comment by drybjed** [comment]
Thanks! Looking at this article it seems that live restore option has certain tradeoffs, so it should probably be optional and disabled by default.

**Comment by tallandtree** [comment]
Agree. I've tested it though and it works, but I don't use it as well. As we use docker in development environment and for JIRA and Confluence, it is not too bad to have a little downtime sometimes.
