### ISSUE TITLE
Add certificate-based client-server authentication between docker-daemon and private registry

### ISSUE THREAD

**Issue by tallandtree** [debops/ansible-docker#24]
Add certificate-based client-server authentication between docker-daemon and private registry. https://docs.docker.com/engine/security/certificates/

I will propose a change for this.

**Comment by drybjed** [comment]
Sounds like a good idea, however DebOps does not have a role for `docker-registry`. That would be needed to make sure that everything works. And I've got a plan.

The [docker-registry package](https://packages.debian.org/stretch/docker-registry) is available in Debian Stretch. Looking at the [source package build dependencies](https://packages.debian.org/source/stretch/docker-registry) it seems that we won't see it in `jessie-backports` repository anytime soon. But I have a better idea - let's make DebOps compatible with Debian Stretch. :-)

This gives the project a fighting chance to be ready to work with next Debian Stable release before the freeze. The preferred way to install Debian Stretch at present is to install minimal Debian Jessie and perform an `apt-get dist-upgrade`, with the APT repositories switched to Stretch. After that, you should be able to manage that host with DebOps as normal. Of course, this won't be the main target for DebOps, and you hopefully won't use this system in production, but this will definitely help with future support.

First step to make this process easy to do would be to write a playbook that converts a minimal Debian Jessie into Debian Stretch. The playbook wich should be able to do it [is already written](https://github.com/debops/debops-playbooks/blob/master/playbooks/tools/dist-upgrade.yml), it just needs to be updated to current OS releases. I'll look into it this week.

After that is ready, it should be easy to run DebOps on Debian Testing and find out what roles need to be updated. I've already found a few - `debops.apt` needs to support Testing sources; `debops.lxc` needs to have its bootstrap script updated, there are probably more. One benefit of getting to Stretch through Jessie is that we still can use the old network interfaces like `eth0`, so `debops.ifupdown` should still work fine.

After all that, we can write a role for `docker-registry` and update `debops.docker` to support client certificates. About that - it's a shame that Docker doesn't let you specify client certs in a config file, but instead it uses a custom directory structure... Well, no matter. The CA certificate can be handled by `debops.pki` already via system certificate store. I have an idea to symlink a PKI realm directory to `/etc/docker/certs.d/`, add `<realm>.cert` and `<realm>.key` symlinks that point to the respective `default.crt` and `default.key` symlinks. I wonder if that will work?

**Comment by tallandtree** [comment]
You don't need a debian docker registry package to test with a docker
registry. A simple playbook that uses ansible module docker_container can
run a docker registry in a docker container with certificates. I will
provide you with a playbook example.
However, moving to debian stretch also sounds like a solid idea.

**Comment by tallandtree** [comment]
Findings from testing with docker registry:2.5 container: 
1. all machines which are configured by debops role: debops.docker by default trust all registries that run on one of those machines and use the same /etc/pki/realms/domain certificates. 
2. by default a docker host trusts a registry that runs in it's own daemon even if the registry is configured with it's own certificate.
3. If a private registry runs on a non-debops managed machine or another debops-managed server but with it's own certificate, the CA-certificate of the registry must be added to /etc/docker/certs.d/registry-fqdn:registry-port of the debops machine that wishes to access the registry.

**Comment by drybjed** [comment]
@tallandtree Can you check if adding the certificate to the system store in `/etc/ssl/certs/` via `/usr/local/share/ca-certificates/` works for external registries? This would allow easy management of these CA certificates via `debops.pki`.

**Comment by tallandtree** [comment]
yes, that works:
1. add root CA (used to sign the registry certificate) to /usr/local/share/ca-certificates
2. update-ca-certificates
3. systemctl restart docker

Note that docker daemon needs to be restarted, else the certificate is still not trusted. It is not required to reload the daemon (systemctl daemon-reload).

**Comment by drybjed** [comment]
Great, in that case when you add the CA certificates through the `debops.pki`, they should be in place when `debops.docker` is executed, and additional restart shouldn't be needed.

Did you test support for client certificates as well?

**Comment by tallandtree** [comment]
Finally able to test properly. I had some issues with connecting via docker client to docker server, because you have to connect on ip address and not DNS name and I forgot to add the ip address of the docker server to the no_proxy variable... 
Command to connect to a remote docker host:

```
docker -H tcp://<IP>:<PORT> --tlsverify <docker command>
```

But I get the following error:

```
docker -H tcp://192.168.56.9:2376 --tlsverify images
An error occurred trying to connect: Get https://192.168.56.9:2376/v1.24/images/json: x509: cannot validate certificate for 192.168.56.9 because it doesn't contain any IP SANs
```

**Comment by drybjed** [comment]
Well, yeah, the certificates generated by `debops.pki` by default don't contain IP addresses for the hosts, but you can either enable that in the default certs, or add custom PKI realm with certificates that contain the IP addresses. Just update the `pki_default_realms` list or add a realm in the other lists with configuration like this:

```
pki_realms:
  - name: '<domain or custom-PKI-realm>'
    acme: False (Let's Encrypt doesn't support IP addresses, AFAIR)
    subject_alt_names:
      - 'ip:{{ ansible_default_ipv4.address }}'
```

After regenerating the certificates (you need to remove the PKI realm directory to recreate them) you should be able to connect to the host over HTTPS via it's IP address.

**Comment by drybjed** [comment]
I'm closing this issue for now so that it doesn't block the merge of DebOps roles into unified `git` repository. It might be revisited later, when DebOps has support for `docker-registry` service.
