### ISSUE TITLE
docker daemon failed to start on some systemd systems

### ISSUE THREAD

**Issue by dmitryint** [debops/ansible-docker#27]
Debian jessie in shipment has the following file: `/lib/systemd/system/docker.service.d/custom.conf` which is in conflict with `/etc/docker/daemon.json`

```
cat /lib/systemd/system/docker.service.d/custom.conf
[Service]
EnvironmentFile=-/etc/default/docker
ExecStart=
ExecStart=/usr/bin/docker daemon $DOCKER_OPTS -H fd://
```

```
cat /etc/docker/daemon.json
{
    "graph": "/var/lib/docker",
    "hosts": [
        "fd://",
        ""
    ]
}
```

Therefore, the Docker service fail with the error:

```
 docker[25026]: time="2016-09-15T09:19:20-07:00" level=fatal msg="unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [fd://], from file: [fd:// ])\n"
```

**Comment by drybjed** [comment]
Hmmm. Interesting. Did you enable Docker from upstream?

**Comment by dmitryint** [comment]
my role looks like:

```
    - role: debops.docker
      tags: [ 'role::docker' ]
      docker__upstream: true
      docker__upstream_key: 58118E89F3A912897C070ADBF76221572C52609D
      docker__upstream_repository: 'deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release }} main'
      docker__tcp: false
      docker__base_packages: [ 'aufs-tools' ]
```

**Comment by drybjed** [comment]
Then I guess this is a recent change in the upstream Docker to check if different values are in the config file vs the command line. Thanks for the heads up, role needs to be updated to take this into account.

**Comment by drybjed** [comment]
@tallandtree Did you see anything similar in your environment?

**Comment by dmitryint** [comment]
Thank you @drybjed! I'll wait for updates.

**Comment by drybjed** [comment]
@dmitryint BTW, you don't need to set the `docker__upstream_key` and `docker__upstream_repository` as the role parameters, since they are in the role default variables... Unless you changed the APT repository source.

**Comment by tallandtree** [comment]
@drybjed, I have not seen it yet, but will do some tests and let you know.

**Comment by tallandtree** [comment]
I've tested with Debian Jessie but no such issue.
I've got the following settings:

```
docker__upstream: True
docker__live_restore: False
docker__debug: False
docker__ferment: False
```

There is no `/lib/systemd/system/docker.service.d/` folder created on my test machine after installation of docker via the debops.docker role. 

@dmitryint, is it possible you created it yourself?

**Comment by mellowplace** [comment]
I have this issue now, first I ran the role so it installed docker.io then I set ```docker__upstream: True``` and ran it again to install the upstream version.

**Comment by mellowplace** [comment]
Work around for me...

```sudo apt-get remove docker-engine```
```sudo rm -r /etc/docker/``` <-- interesting this was still here with both docker.io and docker-engine removed
Reran the playbook to install upstream docker

All worked fine then.

**Comment by marpada** [comment]
+1

**Comment by tallandtree** [comment]
With which version of debian/ubuntu have you experienced this?

**Comment by marpada** [comment]
Ubuntu 16.04, with and without upstream. mellowplace's workaround did the trick

**Comment by drybjed** [comment]
OK, so I suppose that the problem occurs when the `docker.io` package from the distribution was installed first and then upstream version was enabled. Role could add some `dpkg` hook script that cleans any artifacts left after `docker.io` package is removed, similar to [how debops.nullmailer clean up works](https://github.com/debops/ansible-nullmailer/blob/master/templates/usr/local/lib/debops-nullmailer-dpkg-cleanup.j2).

**Comment by drybjed** [comment]
The `debops.docker` role should enable upstream Docker by default on Debian Stretch; more OS releases might be added in the furure if needed.

I'm closing this issue so that it doesn't block the merge of DebOps roles into one `git` repository. It might be revisited in the future with the `dpkg` cleanup hook if needed.
