### ISSUE TITLE
Support for Latest version of docker-ce

### ISSUE THREAD

**Issue by tallandtree** [debops/ansible-docker#32]
Docker split their distributions into docker-ce and docker-ee. New gpg keys are applied. If you use the old gpg keys and old package names, the latest version (docker-ce) is installed without error message. 
But it would be better to add the new gpg key and latest package names. Also it should be possible to install the docker-ee version. If I've time, I'll make the changes and look at the other issues as well.

**Comment by drybjed** [comment]
Sounds good. I'll check it out when I have some time, thanks for the heads up.

**Comment by tallandtree** [comment]
started with this

**Comment by drybjed** [comment]
The role should now work with upstream Docker-CE releases. Thanks, @tallandtree!
