### ISSUE TITLE
docker__storage_driver default setting not correct for debian jessie

### ISSUE THREAD

**Issue by tallandtree** [debops/ansible-docker#40]
The default setting for docker__storage_driver does not work for Debian Jessie.

Docker daemon does not start. Error message from systemctl -l status docker:
level=error msg="'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded."

Can be resolved by removing "storage-driver": "overlay" from /etc/docker/daemon.json.

**Comment by tallandtree** [comment]
Will be included in new version for: https://github.com/debops/ansible-docker/issues/32

**Comment by drybjed** [comment]
This should be solved in the latest version of the `debops.docker` role. I'm closing this issue.
