### ISSUE TITLE
Conditional dependency on ferm?

### ISSUE THREAD

**Issue by ariddell** [debops/ansible-docker#5]
If `docker_ferment` is False, ferm isn't needed, right? Can the dependency be made conditional somehow?

**Comment by drybjed** [comment]
Sure, `debops.docker` role dependencies will be moved to the role playbook in `debops-playbooks` repository in the future. After that you can either use the provided playbook or write your own.

**Comment by ariddell** [comment]
But the ferm dependency is specified in debops.docker's meta.yml file.
How does one work around that?

**Comment by drybjed** [comment]
@ariddell When you update the role, dependneices should be gone now. I want to do something similar to all of the roles included in DebOps, [this is the commit in debops.docker](https://github.com/debops/ansible-docker/commit/23add25a5c8329328e12a94d868b67314f5d876b) and [this is in debops-playbooks](https://github.com/debops/debops-playbooks/commit/e51a2538d243ea2d7e5a8d2e26d53b2f998e844d) if you're wondering about the specifics.

**Comment by ariddell** [comment]
Wonderful! Thanks.
