### ISSUE TITLE
Stretch not detected

### ISSUE THREAD

**Issue by src386** [debops/ansible-docker#51]
According to: https://docs.debops.org/en/latest/ansible/roles/debops.docker/defaults.html

    docker__upstream: '{{ True
                      if (docker__distribution_release == "stretch")
                      else False }}'

if Stretch is detected, the docker upstream should be used.

However : 

    root@debian9:~# ansible-galaxy install debops.docker
    - downloading role 'docker', owned by debops
    - downloading role from https://github.com/debops/ansible-docker/archive/v0.4.1.tar.gz
    - extracting debops.docker to /etc/ansible/roles/debops.docker
    - debops.docker was installed successfully

    root@debian9:~# cat playbook.yml 
        - hosts: localhost

          roles:
            - debops.docker

    root@debian9:~# ansible-playbook playbook.yml 
    [WARNING]: provided hosts list is empty, only localhost is available

    PLAY [localhost] ***************************************************************

    TASK [setup] *******************************************************************
    ok: [localhost]

    TASK [debops.docker : Get upstream APT GPG key] ********************************
    skipping: [localhost]

    TASK [debops.docker : Configure upstream APT repository] ***********************
    skipping: [localhost]

    TASK [debops.docker : Make sure that systemd directory exists] *****************
    ok: [localhost]

    TASK [debops.docker : Make sure that docker.service.d directory exists] ********
    ok: [localhost]

    TASK [debops.docker : Remove other version if upstream is modified] ************
    ok: [localhost] => (item=[u'docker-ce'])

    TASK [debops.docker : Remove startup file(s) if present] ***********************
    skipping: [localhost] => (item=/etc/systemd/system/docker.service.d/http-proxy.conf) 
    skipping: [localhost] => (item=/etc/docker/daemon.json) 
    skipping: [localhost] => (item=/etc/default/docker) 
    skipping: [localhost] => (item=/lib/systemd/system/docker.service) 
    skipping: [localhost] => (item=/etc/systemd/system/docker.service) 

    TASK [debops.docker : Install required packages] *******************************
    failed: [localhost] (item=[u'apt-transport-https', u'ca-certificates', u'curl', u'gnupg2', u'software-properties-common', u'docker.io', u'aufs-tools', u'python-pip', u'python-setuptools', u'python-virtualenv', u'virtualenv', u'bridge-utils']) => {"failed": true, "item": ["apt-transport-https", "ca-certificates", "curl", "gnupg2", "software-properties-common", "docker.io", "aufs-tools", "python-pip", "python-setuptools", "python-virtualenv", "virtualenv", "bridge-utils"], "msg": "No package matching 'docker.io' is available"}
	to retry, use: --limit @/root/playbook.retry

    PLAY RECAP *********************************************************************
    localhost                  : ok=4    changed=0    unreachable=0    failed=1

The playbook tries to install **docker.io**, meaning not using the upstream.

Ansible version:

    root@debian9:~# ansible --version
    ansible 2.2.1.0
      config file = /etc/ansible/ansible.cfg
      configured module search path = Default w/o overrides

Workaround:

      vars:
       - docker__upstream: 'True'

**Comment by drybjed** [comment]
The documentation available on the https://docs.debops.org/ is current for the roles included in the [DebOps monorepo](https://github.com/debops/debops/). The separate DebOps roles are currently deprecated, I'm waiting for the Ansible team to implement support for multi-role repositories in Ansible Galaxy to decide how to re-introduce DebOps roles there.

You can see this fixed in https://github.com/debops/debops/commit/8f4c4b5cc0725482b603614d2e10e16e1d393708

**Comment by src386** [comment]
$ ansible-galaxy install debops.docker
    - downloading role 'docker', owned by debops
    - downloading role from https://github.com/debops/ansible-docker/archive/v0.4.1.tar.gz
    - extracting debops.docker to /home/xavier/bitbucket/ansible/dev/swarm/galaxy/debops.docker
    - debops.docker (v0.4.1) was installed successfully

0.4.1 tag does not include the fix

**Comment by drybjed** [comment]
I tagged the lastest changes in this role as `v0.4.2` and updated Ansible Galaxy. @src386, can you update the role and see if it works as expected?
