### ISSUE TITLE
Permit bunch of ports on docker host

### ISSUE THREAD

**Issue by dddpaul** [debops/ansible-docker#7]
Hi, Maciej!

Thanks again for you great debops project.

I need some feature in debops.docker that I'd like to discuss. In one of your latest commits ferm configuration is defined like thit:

```
  - type: 'accept'
    dport: [ '{{ docker_tcp_port }}' ]
    saddr: '{{ docker_tcp_allow }}'
    accept_any: False
    weight: '50'
    role: 'docker'
    name: 'rest_api_rules'
```

But in my case I'd like to allow not just single `docker_tcp_port` but a list of ports (Swarm manager, Consul ports etc).

I certainly could redefine `docker_ferm_dependent_rules` completely, but this is too excessive - in my opinion.

The other way is to extend `docker_tcp_port` like this (roughly):

```
  - type: 'accept'
    dport: [ '{{ docker_tcp_port }}', '{{ rest_api_ports }}' ]
    saddr: '{{ docker_tcp_allow }}'
    accept_any: False
    weight: '50'
    role: 'docker'
    name: 'rest_api_rules'
```

And later I can redefine `rest_api_ports` in my playbook.

What do you think about this?

**Comment by drybjed** [comment]
Sounds like a good idea. I would go with `docker_custom_tcp_ports` though, to keep the variable name confined to the `debops.docker` role. I can add it in a bit.
